Generate clear error when a nameless contract argument is used  (#1260)
### What

Resolve #1198

What the error looks like now - 

```

error: argument not supported
 --> src/lib.rs:9:18
  |
9 |     pub fn empty(_: u64) {}
  |                  ^

error: argument not supported
 --> src/lib.rs:9:28
  |
9 |     pub fn empty(dog: u64, _: u64) {}
  |                            ^
```

---------

Co-authored-by: Leigh McCulloch <351529+leighmcculloch@users.noreply.github.com>