Make trait functions that have default implementations callable (#1507)
_~This pull request is an experiment. At the moment it exists to
evaluate if a solution like this is ergonomic and meaningful. It might
lead to being merged with some further tuning and tidying.~ It came out
of the idea I shared at
https://github.com/stellar/rs-soroban-sdk/issues/1451#issuecomment-3068036433,
that leverages the idea to use declarative macros (thanks to
@willemneal) that can be code generated as a way to generate macro code
for traits which can be later called by a contract implementing._

### What

Make trait functions that have default implementations callable on
contracts.

### Example

Contract developer implements trait that has some default behaviour:

```rust
#![no_std]
use soroban_sdk::{contract, contractimpl, Env};
use library::Pause;

#[contract]
pub struct Contract;

#[contractimpl]
impl Pause for Contract {}
```

Library developer defines trait with some default behaviour:

```rust
#![no_std]
use soroban_sdk::{contracttrait, symbol_short, Env};

#[contracttrait]
pub trait Pause {
    fn pause(env: &Env, paused: bool) {
        env.storage().persistent().set(&symbol_short!("paused"), &paused)
    }

    fn paused(env: &Env) -> bool {
        env.storage().persistent().get(&symbol_short!("paused")).unwrap_or(false)
    }
}
```

A working example is at:
- https://github.com/leighmcculloch/stellar--rs-soroban-sdk--i1451

### Why

When defining traits that have default functions, and implementing them
for a contract, the default functions do not get exported. The default
functions do get exported when overridden by the contract. That
difference in behaviour is surprising, and surprising behaviour can lead
to bugs.

The solution requires the developer to learn very little. The code looks
almost identical to any other Rust application wanting to use a trait
with a default implementation, albeit the need to place the macro on the
trait.

Resolve #1451 

### How It Works

<img width="2034" height="966" alt="diagram"
src="https://github.com/user-attachments/assets/ca56ee8c-1347-42e8-9cb6-d7804e6bb6db"
/>

### Try It Out

Try this pull request out locally:

1. Check out the working example at
https://github.com/leighmcculloch/stellar--rs-soroban-sdk--i1451

or

1. Edit your `Cargo.toml` file so that the `soroban-sdk` imports look
like this:
    ```toml
    [dependencies]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk",
branch = "i1451" }

    [dev-dependencies]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk",
branch = "i1451", features = ["testutils"] }
    ```

2. Add `#[contracttrait]` to the top of any trait your contract is
implementing.

4. Add a function to the trait, or modify an existing function, to have
a default implementation.

### Merging
This change is intended to target a major v24 release, maybe v23.

### TODO
- [x] Pass down the `export` parameter
- [x] Adopt for all interfaces built into the SDK
- [x] Test change against soroban-examples
- [x] Test change against @axelarnetwork's `stellar-axelar-std` lib to
look for unexpected interactions with proc-macros wrapping contractimpl,
and other advanced patterns
- [x] Consider if `#[contracttrait]` should automatically inject
`#[contractspecfn]`, `#[contractargs]`, `#[contractclient]`
- [x] Split the `#[contracttrait]` into an external macro that supports
the general case and a separate internal macro for just generating the
dec macro without any other injections
- [x] Move the test vector I've written into the repo.
- [x] Convert some of the test vector manual testing into automated
tests in the repo.
- [ ] Find a way to present a better compile error when
`#[contracttrait]` is missing on an trait that is being used with
`#[contractimpl]`, currently the error is not intuitive:
    ```
    error: cannot find macro `MyTrait` in this scope
      --> src/contract.rs:15:6
    15 | impl MyTrait for MyContract {
       |      ^^^^^^^
    ```
- [x] Fix ctor setup for default fns
https://github.com/stellar/rs-soroban-sdk/pull/1526
- [x] Include doc strings in generated contract specs of default impl
functions
https://github.com/stellar/rs-soroban-sdk/pull/1507#issuecomment-3206485276
- [x] Remove visible internal named macro
https://github.com/stellar/rs-soroban-sdk/pull/1507#issuecomment-3177252864
- [x] Add a test that exercises contracttrait with every supported
val/sdk type.
- [x] Add a test that exercises contracttrait with contracttype types.
- [x] Add a test that exercises contracttrait across crate boundaries.
- [x] Investigate why specs are being duplicated for contracttrait fns.
- [ ] Fix bug with ctor inclusion on contracttrait fns (see
https://github.com/stellar/rs-soroban-sdk/pull/1507#issuecomment-3654976496)

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>